name: Check and deploy

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  # general
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_ORG: ${{ github.event.organization.name }}
  GITHUB_REPO: ${{ github.event.repository.name }}
  GITHUB_BRANCH: ${{ github.ref_name }}

  # docker
  CONTAINER_REGISTRY: ghcr.io
  CONTAINER_IMAGE: ${{ github.event.organization.name }}/${{ github.event.repository.name }}

  # deployment
  K8S_CLUSTER: k8s-bandsy
  K8S_CONFIG_PATH: ${{ env.GITHUB_WORKSPACE }}/.kubeconfig
  HELM_RELEASE_NAMESPACE: winget-run-dev
  HELM_RELEASE: ${{ github.event.repository.name }}
  HELM_CHART_DIR: ./chart

jobs:
  check:
    name: General code checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6
      - name: Install dependencies
        run: pnpm install
      - name: Ensure correct formatting
        run: pnpm format:check
      - name: Ensure correct linting
        run: pnpm lint:check
      - name: Ensure tests pass requirements
        run: pnpm test:check
      - name: Ensure code builds
        run: pnpm build:check
  build:
    name: Build container image
    if: github.event_name == 'push'
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to github container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ secrets.CONTAINER_REGISTRY_USER }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.CONTAINER_IMAGE }}:${{ env.GITHUB_SHA }},${{ env.CONTAINER_IMAGE }}:${{ env.GITHUB_BRANCH }},${{ env.CONTAINER_IMAGE }}:latest
  deploy:
    name: Deploy to kubernetes
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Save kubeconfig
        uses: digitalocean/action-doctl@v2
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        with:
          args: kubernetes cluster kubeconfig show ${{ env.K8S_CLUSTER }} > ${{ env.K8S_CONFIG_PATH }}
      - name: Install helm
        run: |-
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
      - name: Update deployment
        run: helm upgrade ${{ env.HELM_RELEASE }} ${{ env.HELM_CHART_DIR }} --install --atomic --namespace ${{ env.HELM_RELEASE_NAMESPACE }} --kubeconfig=${{ env.K8S_CONFIG_PATH }} --set-string sha=${{ env.GITHUB_SHA }}
